### ISSUE TITLE
File path option

### ISSUE THREAD

**Issue by soniktrooth** [eablokker/nova-tabs-sidebar#7]
In some languages (e.g. javascript) you can end up with a lot of files with the same name. 

![image](https://github.com/eablokker/nova-tabs-sidebar/assets/597617/dd93734d-5d30-45fc-9896-ac8f3876130d)

This makes the _path_ more important than the file name itself—and in particular the path from the file back up the tree. As you can see in the screen shot, when the path is long there’s no way to tell what folder the index.js is in and therefore impossible to know which is which. 

A better layout for this instance would be a right aligned file path:
- file name to the right
- path extends to the left 
- when the path is longer than the window space append ellipsis on the left side. 

Thanks for your work on this—it reminds me of how Espresso handled tabs. Been a while since I’ve used that.

**Comment by eablokker** [comment]
Thanks, I tried to make it like Espresso :) Wish it hadn't been abandoned.

The Nova extension API doesn't have an option to do the ellipsis on the left side, only the right side.

Also the icon and brighter text has to be on the left, and the darker text on the right.

Do you have any other suggestions? What about a max path length setting where I could truncate it in the middle so you could see both ends of it? (no option in API to auto-truncate in the middle, I'd have to truncate the string before sending it to the UI)

Or just an option to reverse the path order so it would start at the other end?

You should be able to see the full path in a hover tooltip.

Also looks like I'm seeing a bug in your screenshot where the first parent folder is appearing twice. If I fix that, that should shorten the length.

**Comment by eablokker** [comment]
I just released an update that fixes the double parent folder bug, and adds an option to show the paths in forward or reverse order. Let me know if that helps.

**Comment by soniktrooth** [comment]
It’s a bummer that the API is getting in the way. Oh well. 

A max path length might work but you still don’t know how wide someone will have their sidebar so it’s a little arbitrary. 

After fixing that bug, I guess what you have now is probably the best it can get unless Panic gives you some more options in a future release. 

Thanks!
